# Generated by Django 5.2.10 on 2026-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_lovedone_eleven_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='catch_phrase',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
