# Generated by Django 5.2.10 on 2026-02-16 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_lovedone_catch_phrase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lovedone',
            name='voice_loved_profile_439769_idx',
        ),
        migrations.RemoveField(
            model_name='lovedone',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='lovedone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loved_ones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lovedone',
            index=models.Index(fields=['created_at'], name='voice_loved_created_3febd0_idx'),
        ),
    ]
