# Generated by Django 5.2.10 on 2026-02-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_remove_lovedone_voice_loved_profile_439769_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lovedone',
            name='last_conversation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
